import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import {
  Aero,
  usePrisma,
  useDrizzle,
  AeroCLI,
} from '../src/index.js';
import { createTestClient } from '../src/testing/test-client.js';

describe('AeroJS CLI & ORM Integrations (Drizzle & Prisma)', () => {
  const generatedAppDir = join(process.cwd(), 'app');
  const generatedDbDir = join(process.cwd(), 'database');

  afterAll(() => {
    // Clean up files generated by CLI tests
    if (existsSync(generatedAppDir)) {
      rmSync(generatedAppDir, { recursive: true, force: true });
    }
    if (existsSync(generatedDbDir)) {
      rmSync(generatedDbDir, { recursive: true, force: true });
    }
  });

  describe('Prisma & Drizzle ORM Integrations', () => {
    it('integrates Prisma Client with IoC container and exposes ctx.prisma', async () => {
      const app = new Aero();

      const mockPrisma = {
        user: {
          findMany: async () => [{ id: 1, name: 'Grace Prisma' }],
        },
      };

      app.usePrisma(mockPrisma);

      app.get('/prisma-users', async (ctx) => {
        expect(ctx.prisma).toBe(mockPrisma);
        const users = await ctx.prisma.user.findMany();
        ctx.status(200).json(users);
      });

      const client = createTestClient(app);
      const res = await client.get('/prisma-users');

      expect(res.status).toBe(200);
      expect(res.json()[0].name).toBe('Grace Prisma');
    });

    it('integrates Drizzle ORM with IoC container and exposes ctx.drizzle', async () => {
      const app = new Aero();

      const mockDrizzle = {
        select: () => ({
          from: () => ({
            where: async () => [{ id: 101, title: 'Drizzle Post' }],
          }),
        }),
      };

      app.useDrizzle(mockDrizzle);

      app.get('/drizzle-posts', async (ctx) => {
        expect(ctx.drizzle).toBe(mockDrizzle);
        const posts = await ctx.drizzle.select().from().where();
        ctx.status(200).json(posts);
      });

      const client = createTestClient(app);
      const res = await client.get('/drizzle-posts');

      expect(res.status).toBe(200);
      expect(res.json()[0].title).toBe('Drizzle Post');
    });
  });

  describe('Aero CLI Tooling', () => {
    it('executes --version and --help without errors', async () => {
      const versionExit = await AeroCLI.run(['--version']);
      expect(versionExit).toBe(0);

      const helpExit = await AeroCLI.run(['--help']);
      expect(helpExit).toBe(0);
    });

    it('scaffolds controllers via "make:controller"', async () => {
      const exitCode = await AeroCLI.run(['make:controller', 'Product']);
      expect(exitCode).toBe(0);

      const controllerPath = join(process.cwd(), 'app/controllers/ProductController.ts');
      expect(existsSync(controllerPath)).toBe(true);
    });

    it('scaffolds models and migrations via "make:model -m"', async () => {
      const exitCode = await AeroCLI.run(['make:model', 'Product', '-m']);
      expect(exitCode).toBe(0);

      const modelPath = join(process.cwd(), 'app/models/Product.ts');
      expect(existsSync(modelPath)).toBe(true);
      expect(existsSync(join(process.cwd(), 'database/migrations'))).toBe(true);
    });

    it('scaffolds middleware via "make:middleware"', async () => {
      const exitCode = await AeroCLI.run(['make:middleware', 'AuditLog']);
      expect(exitCode).toBe(0);

      const middlewarePath = join(process.cwd(), 'app/middleware/AuditLog.ts');
      expect(existsSync(middlewarePath)).toBe(true);
    });

    it('executes database migration commands via CLI', async () => {
      const statusExit = await AeroCLI.run(['migrate:status']);
      expect(statusExit).toBe(0);

      const migrateExit = await AeroCLI.run(['migrate']);
      expect(migrateExit).toBe(0);

      const rollbackExit = await AeroCLI.run(['migrate:rollback']);
      expect(rollbackExit).toBe(0);
    });
  });
});
