import { describe, it, expect, beforeEach } from 'vitest';
import { Notification, Notifications, notify } from '../src/notifications/index.js';
import { Mail, MailMessage } from '../src/mail/index.js';

class InvoiceGeneratedNotification extends Notification {
  constructor(public invoiceName: string, public invoiceId: number) {
    super();
  }

  public via(notifiable: any): string[] {
    return ['mail', 'database', 'broadcast'];
  }

  public toMail(notifiable: any): MailMessage {
    const msg = new MailMessage();
    msg.subject(`Invoice Ready: ${this.invoiceName}`)
       .text(`Hello ${notifiable.name}, your invoice is ready.`);
    return msg;
  }

  public toDatabase(notifiable: any): Record<string, any> {
    return {
      invoiceName: this.invoiceName,
      invoiceId: this.invoiceId,
      message: 'Invoice generated by billing system',
    };
  }

  public toBroadcast(notifiable: any) {
    return {
      channel: `user.${notifiable.id}`,
      event: 'InvoiceReady',
      data: { invoiceId: this.invoiceId },
    };
  }
}

describe('AeroJS Multi-Channel Notification System', () => {
  let user: { id: number; name: string; email: string };

  beforeEach(() => {
    Notifications.restore();
    Mail.restore();
    user = {
      id: 501,
      name: 'Rahim Ahmed',
      email: 'rahim@example.org',
    };
  });

  it('dispatches multi-channel notification via Mail, Database, and Broadcast', async () => {
    const memoryMail = Mail.fake();

    const notif = new InvoiceGeneratedNotification('Monthly Statement', 9021);
    await Notifications.send(user, notif);

    // Verify Mail was delivered
    expect(memoryMail.sentMessages.length).toBe(1);
    expect(memoryMail.sentMessages[0]?.subjectLine).toBe('Invoice Ready: Monthly Statement');
    expect(memoryMail.sentMessages[0]?.toAddresses).toContain('rahim@example.org');
  });

  it('supports custom channels via Notifications.extend()', async () => {
    let smsSent: { to: string; msg: string } | null = null;

    Notifications.extend('sms', (notifiable, notification: any) => {
      smsSent = {
        to: notifiable.phone,
        msg: `Alert: ${notification.itemName}`,
      };
    });

    class SmsOnlyNotification extends Notification {
      constructor(public itemName: string) {
        super();
      }
      public via() {
        return ['sms'];
      }
    }

    const recipientWithPhone = { id: 7, phone: '+8801700000000' };
    await Notifications.send(recipientWithPhone, new SmsOnlyNotification('Order Shipped'));

    expect(smsSent).toEqual({
      to: '+8801700000000',
      msg: 'Alert: Order Shipped',
    });
  });

  it('supports testing fakes and assertions via Notifications.fake()', async () => {
    Notifications.fake();

    const notif = new InvoiceGeneratedNotification('Consulting Service', 400);
    await notify(user, notif);

    Notifications.assertSentTo(user, InvoiceGeneratedNotification, (n) => n.invoiceName === 'Consulting Service');

    const otherUser = { id: 999, name: 'Karim', email: 'karim@example.com' };
    Notifications.assertNotSentTo(otherUser, InvoiceGeneratedNotification);
  });
});
